### ISSUE TITLE
TPS-C2CRI-App-0052: Not support authorized test suite 

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/c2c-ri#29]
### Summary
Cannot complete below steps by following test plan (_TPS-C2CRI-Application-v2-10 FINAL 2021-06-01):
Step 4 & 7:  File->New: Displayed "Predefined Test Suite" not "Authorized Predefined Test Suite"
Step: 14: There is no "NTCIP2306v01_69Signed.jar, but there is an "NTCIP2306v01_69OpenSource.jar"
Step 86: Cannot sign jar file because tester does not have key password
Step  96: Display incorret test suite name
Step 107 moving onward incorrect because the files in customTestSuites folders are different from the expected outcome (Specifically EmulationData folder is missing). 

### Version

candidate_r1 release branch

### Expected Behavior

TPS-C2CRI-App-0052 steps can be completed without issues

### Actual Behavior

Cannot complete TPS-C2CRI-App-0052 steps

### Steps to Reproduce the Actual Behavior

Launch C2CRI OC and EC.
Follow test plan to finish TPS-C2CRI-App-0052 steps.

**Comment by maefromm** [comment]
@SaikrishnaBairamoni  closing this out since there's duplicate issue in Jira C2CRI-303.
